import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { X, Copy, Sparkles, BookOpen, AlertCircle, Loader2, BrainCircuit, ChevronDown, ChevronRight, Settings2, Eye, User } from 'lucide-react';
import type { HistoryRecord, Aspect, Perspective } from '../types';
import { generateBiography, buildPrompt } from '../utils/deepseek';

interface BiographyModalProps {
  isOpen: boolean;
  onClose: () => void;
  history: HistoryRecord[];
  finalResultTitle: string;
  dominantAspect: Aspect;
  matchedHourName: string;
}

export const BiographyModal: React.FC<BiographyModalProps> = ({
  isOpen,
  onClose,
  history,
  finalResultTitle,
  dominantAspect,
  matchedHourName
}) => {
  const [apiKey, setApiKey] = useState('sk-cf51ba1983404d40b60fc3d6cf37135e');
  const [isGenerating, setIsGenerating] = useState(false);
  const [biography, setBiography] = useState('');
  const [reasoning, setReasoning] = useState('');
  const [isReasoningCollapsed, setIsReasoningCollapsed] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showPromptCopy, setShowPromptCopy] = useState(false);
  const [showStoryCopy, setShowStoryCopy] = useState(false);
  const [isMobileSettingsOpen, setIsMobileSettingsOpen] = useState(true);
  const [perspective, setPerspective] = useState<Perspective>('protagonist');
  const [showQuotaWarning, setShowQuotaWarning] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom during generation
  useEffect(() => {
    if (isGenerating && contentRef.current) {
      const { scrollHeight, scrollTop, clientHeight } = contentRef.current;
      // Sticky scroll: only scroll if user is already near bottom (threshold 150px)
      const isNearBottom = scrollHeight - scrollTop - clientHeight < 150;
      
      if (isNearBottom) {
        contentRef.current.scrollTop = scrollHeight;
      }
    }
  }, [biography, isGenerating]); // Removed reasoning from dependencies to prevent auto-scroll when reading CoT

  const handleGenerate = async () => {
    if (!apiKey) {
      setError('请输入 DeepSeek API Key');
      return;
    }

    // Check quota warning
    const count = parseInt(localStorage.getItem('biography_gen_count') || '0');
    if (count >= 1 && !showQuotaWarning && apiKey === 'sk-cf51ba1983404d40b60fc3d6cf37135e') {
        setShowQuotaWarning(true);
        return;
    }

    setIsGenerating(true);
    setIsMobileSettingsOpen(false); // Auto-collapse settings on mobile when generation starts
    setError(null);
    setBiography('');
    setReasoning('');
    setIsReasoningCollapsed(false); // Expand reasoning while generating

    try {
      await generateBiography(
        history,
        finalResultTitle,
        dominantAspect,
        matchedHourName,
        apiKey,
        (chunk) => setBiography(prev => prev + chunk),
        (chunk) => setReasoning(prev => prev + chunk),
        perspective
      );
      // Collapse reasoning after generation is complete
      setIsReasoningCollapsed(true);
      // Increment generation count
      localStorage.setItem('biography_gen_count', (count + 1).toString());
    } catch (err: any) {
      setError(err.message || '生成失败，请检查 API Key 或网络连接');
      setIsMobileSettingsOpen(true); // Re-open settings on error
    } finally {
      setIsGenerating(false);
    }
  };

  const handleConfirmQuota = () => {
      setShowQuotaWarning(false);
      // Proceed with generation
      handleGenerate();
  };

  const handleCopyPrompt = () => {
    const prompt = buildPrompt(history, finalResultTitle, dominantAspect, matchedHourName, perspective);
    navigator.clipboard.writeText(prompt);
    setShowPromptCopy(true);
    setTimeout(() => setShowPromptCopy(false), 2000);
  };

  const handleCopyStory = () => {
    if (!biography) return;
    
    const copyrightInfo = `\n\n---\nGenerated by Which Hour Will You Serve?\n© ${new Date().getFullYear()} Which Hour Will You Serve\nSource: ${window.location.href}`;
    const textToCopy = biography + copyrightInfo;
    
    navigator.clipboard.writeText(textToCopy);
    setShowStoryCopy(true);
    setTimeout(() => setShowStoryCopy(false), 2000);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 md:p-8">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-black/80 backdrop-blur-sm"
          />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="relative w-full max-w-4xl h-[85vh] bg-onyx border border-gold/30 shadow-[0_0_50px_rgba(192,160,98,0.1)] flex flex-col overflow-hidden rounded-sm"
          >
            {/* Quota Warning Overlay */}
            {showQuotaWarning && (
                <div className="absolute inset-0 z-[60] flex items-center justify-center p-4 bg-black/90 backdrop-blur-sm">
                    <div className="bg-onyx border border-gold/40 p-6 max-w-md w-full shadow-[0_0_30px_rgba(192,160,98,0.3)] text-center">
                        <AlertCircle className="w-12 h-12 text-gold mx-auto mb-4" />
                        <h3 className="text-xl text-gold font-heading mb-2">额度提醒</h3>
                        <p className="text-parchment/80 text-sm mb-6 leading-relaxed">
                            这是一个完全由个人维护的公益项目，DeepSeek API 的额度非常有限。
                            <br/><br/>
                            如果您觉得有趣，推荐复制 Prompt 前往 <a href="https://chat.deepseek.com/" target="_blank" rel="noreferrer" className="text-gold underline hover:text-white">DeepSeek 官网</a> 自行创建，效果完全一致且免费。
                        </p>
                        <div className="flex flex-col gap-3">
                            <button 
                                onClick={() => {
                                    handleCopyPrompt();
                                    setShowQuotaWarning(false);
                                    window.open('https://chat.deepseek.com/', '_blank');
                                }}
                                className="w-full py-2 border border-gold/40 text-gold hover:bg-gold/10 transition-colors font-heading tracking-wider uppercase text-sm"
                            >
                                复制 Prompt 并前往官网
                            </button>
                            <button 
                                onClick={handleConfirmQuota}
                                className="w-full py-2 bg-gold/10 text-gold/60 hover:text-gold hover:bg-gold/20 transition-colors font-heading tracking-wider uppercase text-xs"
                            >
                                我知道了，继续使用本站额度
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-gold/20 bg-void/50">
              <div className="flex items-center gap-3">
                <BookOpen className="text-gold w-6 h-6" />
                <h2 className="text-2xl text-gold font-heading tracking-wider">书写命运</h2>
              </div>
              <button 
                onClick={onClose}
                className="text-gold/60 hover:text-gold transition-colors"
              >
                <X size={24} />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 flex flex-col md:flex-row overflow-hidden relative">
              
              {/* Mobile Settings Toggle */}
              <div className="md:hidden flex items-center justify-between p-4 border-b border-gold/20 bg-void/40 shrink-0">
                 <div className="flex items-center gap-3">
                   <span className="text-gold/60 text-xs font-heading tracking-widest uppercase">
                     {isGenerating ? '正在书写命运...' : '配置与生成'}
                   </span>
                   {biography && !isGenerating && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleCopyStory();
                        }}
                        className="flex items-center gap-1.5 px-2 py-1 rounded border border-gold/20 bg-gold/5 text-gold/80 hover:bg-gold/10 hover:text-gold transition-colors"
                      >
                        <Copy size={12} />
                        <span className="text-[10px] font-heading tracking-wider uppercase">
                          {showStoryCopy ? '已复制' : '复制全文'}
                        </span>
                      </button>
                    )}
                 </div>
                 <button 
                   onClick={() => setIsMobileSettingsOpen(!isMobileSettingsOpen)}
                   className="text-gold hover:text-white transition-colors flex items-center gap-2"
                 >
                   <span className="text-xs">{isMobileSettingsOpen ? '收起' : '展开'}</span>
                   {isMobileSettingsOpen ? <ChevronDown size={16} /> : <Settings2 size={16} />}
                 </button>
              </div>

              {/* Sidebar (Controls) */}
              <div className={`
                w-full md:w-80 border-b md:border-b-0 md:border-r border-gold/20 bg-void/30 flex-col gap-6 overflow-y-auto shrink-0
                ${isMobileSettingsOpen ? 'flex p-6' : 'hidden'} 
                md:flex md:p-6
              `}>
                <div className="space-y-4">
                  <label className="block text-gold/80 text-sm font-heading tracking-wide">
                    叙事视角
                  </label>
                  <div className="grid grid-cols-2 gap-2">
                    <button
                      onClick={() => setPerspective('protagonist')}
                      className={`p-3 border rounded flex flex-col items-center gap-2 transition-all duration-300
                        ${perspective === 'protagonist' 
                          ? 'bg-gold/20 border-gold text-gold shadow-[0_0_15px_rgba(192,160,98,0.2)]' 
                          : 'bg-black/40 border-gold/20 text-gold/40 hover:border-gold/40 hover:text-gold/60'
                        }`}
                    >
                      <User className="w-5 h-5" />
                      <span className="text-xs font-heading tracking-wider">飞升者</span>
                    </button>
                    <button
                      onClick={() => setPerspective('observer')}
                      className={`p-3 border rounded flex flex-col items-center gap-2 transition-all duration-300
                        ${perspective === 'observer' 
                          ? 'bg-gold/20 border-gold text-gold shadow-[0_0_15px_rgba(192,160,98,0.2)]' 
                          : 'bg-black/40 border-gold/20 text-gold/40 hover:border-gold/40 hover:text-gold/60'
                        }`}
                    >
                      <Eye className="w-5 h-5" />
                      <span className="text-xs font-heading tracking-wider">旁观者</span>
                    </button>
                  </div>
                  <p className="text-xs text-ash/60 leading-relaxed min-h-[2.5em]">
                    {perspective === 'protagonist' 
                      ? '以第一人称体验飞升者的异化与神性。' 
                      : '以无辜者的视角，目睹不可名状的恐怖。'}
                  </p>
                </div>

                <div className="h-px w-full bg-gold/10 my-2" />

                <div className="space-y-4">
                  <label className="block text-gold/80 text-sm font-heading tracking-wide">
                    DeepSeek API Key
                  </label>
                  <input
                    type="password"
                    value={apiKey}
                    onChange={(e) => setApiKey(e.target.value)}
                    placeholder="sk-..."
                    className="w-full bg-black/40 border border-gold/20 rounded p-3 text-parchment text-sm focus:border-gold/60 focus:outline-none transition-colors font-mono"
                  />
                  <p className="text-xs text-ash/60 leading-relaxed">
                    您的 Key 仅用于本次请求，不会被保存。
                    <br />
                    <a href="https://platform.deepseek.com/" target="_blank" rel="noreferrer" className="text-gold/60 hover:text-gold underline">
                      获取 API Key
                    </a>
                  </p>
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={isGenerating || !apiKey}
                  className={`w-full py-3 px-4 flex items-center justify-center gap-2 font-heading tracking-widest uppercase transition-all duration-300 border
                    ${isGenerating || !apiKey
                      ? 'bg-void border-ash/20 text-ash/40 cursor-not-allowed'
                      : 'bg-gold/10 border-gold/40 text-gold hover:bg-gold/20 hover:border-gold hover:shadow-[0_0_15px_rgba(192,160,98,0.2)]'
                    }`}
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="animate-spin w-4 h-4" />
                      书写中...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      开始书写
                    </>
                  )}
                </button>

                {error && (
                  <div className="p-3 bg-red-900/20 border border-red-500/30 rounded text-red-200/80 text-xs flex items-start gap-2">
                    <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
                    <span>{error}</span>
                  </div>
                )}

                <div className="h-px w-full bg-gold/10 my-2" />

                <button
                  onClick={handleCopyPrompt}
                  className="w-full py-2 px-4 flex items-center justify-center gap-2 text-xs font-heading tracking-widest uppercase border border-gold/20 text-gold/60 hover:text-gold hover:border-gold/40 transition-colors"
                >
                  <Copy className="w-3 h-3" />
                  {showPromptCopy ? '已复制 Prompt' : '复制 Prompt 自用'}
                </button>

                <button
                  onClick={handleCopyStory}
                  disabled={!biography || isGenerating}
                  className={`w-full py-2 px-4 flex items-center justify-center gap-2 text-xs font-heading tracking-widest uppercase border transition-colors mt-2
                    ${!biography || isGenerating 
                      ? 'border-gold/10 text-gold/20 cursor-not-allowed' 
                      : 'border-gold/20 text-gold/60 hover:text-gold hover:border-gold/40'
                    }`}
                >
                  <BookOpen className="w-3 h-3" />
                  {showStoryCopy ? '已复制小说' : '复制小说全文'}
                </button>
              </div>

              {/* Main Area (Output) */}
              <div 
                ref={contentRef}
                className="flex-1 p-6 md:p-10 overflow-y-auto bg-parchment/5 scrollbar-thin scrollbar-thumb-gold/20 scrollbar-track-transparent"
              >
                {reasoning && (
                  <div className="mb-8 border border-gold/20 rounded bg-black/20 overflow-hidden">
                    <button 
                      onClick={() => setIsReasoningCollapsed(!isReasoningCollapsed)}
                      className="w-full flex items-center gap-2 p-3 bg-gold/5 hover:bg-gold/10 transition-colors text-gold/60 text-xs font-heading tracking-widest uppercase"
                    >
                      <BrainCircuit className="w-4 h-4" />
                      <span>思维链 (Chain of Thought)</span>
                      {isReasoningCollapsed ? <ChevronRight className="w-4 h-4 ml-auto" /> : <ChevronDown className="w-4 h-4 ml-auto" />}
                    </button>
                    
                    {!isReasoningCollapsed && (
                      <div className="p-4 text-ash/60 font-mono text-sm leading-relaxed whitespace-pre-wrap border-t border-gold/10 bg-black/40">
                        {reasoning}
                        {isGenerating && !biography && (
                          <span className="inline-block w-2 h-4 ml-1 bg-gold/50 animate-pulse align-middle" />
                        )}
                      </div>
                    )}
                  </div>
                )}

                {biography ? (
                  <div className="prose prose-invert prose-gold max-w-none">
                    <ReactMarkdown
                      components={{
                        h1: ({node, ...props}) => <h1 className="text-3xl text-gold font-heading mb-6 border-b border-gold/20 pb-2" {...props} />,
                        h2: ({node, ...props}) => <h2 className="text-2xl text-gold/90 font-heading mt-8 mb-4" {...props} />,
                        h3: ({node, ...props}) => <h3 className="text-xl text-gold/80 font-heading mt-6 mb-3" {...props} />,
                        p: ({node, ...props}) => <p className="text-parchment/90 font-body leading-relaxed mb-4 text-lg" {...props} />,
                        strong: ({node, ...props}) => <strong className="text-gold font-bold" {...props} />,
                        em: ({node, ...props}) => <em className="text-gold/80 italic" {...props} />,
                        blockquote: ({node, ...props}) => <blockquote className="border-l-2 border-gold/40 pl-4 italic text-ash/80 my-4" {...props} />,
                      }}
                    >
                      {biography}
                    </ReactMarkdown>
                    {isGenerating && (
                      <div className="flex justify-center mt-8">
                        <div className="w-2 h-2 bg-gold rounded-full animate-bounce mx-1" style={{ animationDelay: '0s' }} />
                        <div className="w-2 h-2 bg-gold rounded-full animate-bounce mx-1" style={{ animationDelay: '0.2s' }} />
                        <div className="w-2 h-2 bg-gold rounded-full animate-bounce mx-1" style={{ animationDelay: '0.4s' }} />
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="h-full flex flex-col items-center justify-center text-ash/30 gap-4">
                    <BookOpen className="w-16 h-16 opacity-20" />
                    <p className="font-decorative tracking-widest text-sm uppercase">等待书写命运...</p>
                  </div>
                )}
              </div>

            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
